### ISSUE TITLE
Create API

### ISSUE THREAD

**Issue by tonyday567** [tonyday567/numhask-array#4]
Create a numhask-array version for this:

https://pechersky.github.io/haskell-numpy-docs/

**Comment by o1lo01ol1o** [comment]
Do you want do add the numeric tower instances before we pepper ops in willy-nilly?  We also might want to start thinking about module structures for various backends (and also moving to term-level singlton instances en lieu of those verbose `Proxy`s)  

There's also an intero ghci segfault when you give an `Array` a shape of `'[]`, so we might need to move to a non-empty list type.

**Comment by tonyday567** [comment]
Probably good advice, but had already made a start on it and no new operations - once you plug in to numhask, most operations are there already.

**Comment by tonyday567** [comment]
I get this in master:

```
> stack ghci

λ: let b = [3] :: Array '[] Int
λ: b
3
```

And that sure looks like a brilliant, if accidental, definition of a scalar to me!

**Comment by o1lo01ol1o** [comment]
Haven't had time to replicate that `'[]` crash but I concur that is an elegant scalar.  

I was just going over the accelerate and tensorflow apis.  I suspect that shoe-horning them into `Representable` instances is going to lead to some poor performance since the respective compilers would have to be extra smart about recognizing candidates for fusion.  Is there a way of structuring the `numhask` packages such that one could switch between backends?  

Some things to consider:
1) Acclerate calculations require an extra function call to run them
1.1) that call needs a parameter to specify which computation interpreter to use 

2) operations in the numhask that would best be done via tensorflow's broadcasting mechanic should be intercepted and converted behind the scenes
2.1) TF's standard library of ops will likely be more performant than Acclerate

**Comment by tonyday567** [comment]
All good questions.  Performance is on my radar - I just cleaned up my little perf library and am fixing to run Representable through some loops. In the short run, I wanted to experiment with using a flat vector versus using a vector of vector approach.  In other words, start with a Vector representable, and make a 2-array (say) be a Compose (Vector m) (Vector n).

I would say that numhask is so bare bones you can do anything that haskell is capable of. Representable is just one neat way of defining array operations.

The backend of numhask-array is just the vector the Array type wraps.  Make that polymorphic and instances can be defined however.

**Comment by o1lo01ol1o** [comment]
Should the new Accelerate array type shadow the same name as the vanilla array type?  This would make prototyping / debuging easier since it's only a module import to change.

**Comment by tonyday567** [comment]
Closing - this has been created in NumHask.Array.Example (though incomplete)
